export const FETCH_INCOMES = 'FETCH_INCOMES';
export const ADD_INCOME = 'ADD_INCOME';
export const DELETE_INCOME = 'DELETE_INCOME';
export const UPDATE_INCOME = 'UPDATE_INCOME';

export const ADD_EXPENSE = 'ADD_EXPENSE';
export const FETCH_EXPENSES = 'FETCH_EXPENSES';
export const DELETE_EXPENSE = 'DELETE_EXPENSE';
export const UPDATE_EXPENSE = 'UPDATE_EXPENSE';